AuctionatorFullScanFrameMixin = {}

local FULL_SCAN_EVENTS = {
  "AUCTION_ITEM_LIST_UPDATE",
  "AUCTION_HOUSE_CLOSED",
}

-- Enhanced integrated build: cooperative scan processing.
-- The legacy scanner used a fixed 150-row batch followed by an unconditional
-- 10ms sleep. On large Classic/TBC auction houses that inserted seconds of
-- avoidable client-side latency. Time-budgeted batches use the current frame's
-- available CPU instead, while still yielding often enough to keep the UI
-- responsive.
local CACHE_FRAME_BUDGET_MS = 3.0
local CACHE_MIN_ROWS = 75
local CACHE_MAX_ROWS = 1500
local CACHE_DATA_TIMEOUT_SECONDS = 4

local MERGE_FRAME_BUDGET_MS = 3.0
local MERGE_MIN_ROWS = 150
local MERGE_MAX_ROWS = 2500

function AuctionatorFullScanFrameMixin:OnLoad()
  Auctionator.Debug.Message("AuctionatorFullScanFrameMixin:OnLoad")
  Auctionator.EventBus:RegisterSource(self, "AuctionatorFullScanFrameMixin")
  self.state = Auctionator.SavedState
end

function AuctionatorFullScanFrameMixin:ResetData()
  self.scanData = {}
  self.dbKeysMapping = {}
  self.cacheEnumerationComplete = false
  self.cacheTimeoutStarted = false
end

function AuctionatorFullScanFrameMixin:InitiateScan()
  if self:CanInitiate() then
    Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanStart)

    self.state.TimeOfLastGetAllScan = time()

    self.inProgress = true
    self.scanStartProfile = debugprofilestop()
    self.totalAuctions = 0
    self.skippedAuctions = 0
    self.unresolvedAuctions = 0

    self:RegisterForEvents()
    Auctionator.Utilities.Message(AUCTIONATOR_L_STARTING_FULL_SCAN)

    -- Patch to prevent an error being generated by the classic AH code
    if not ITEM_QUALITY_COLORS[-1] then
      ITEM_QUALITY_COLORS[-1] = {r=0, b=0, g=0}
    end

    QueryAuctionItems("", nil, nil, 0, nil, nil, true, false, nil)
    -- 10% complete after making the replicate/get-all request
    Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanProgress, 0.1)
  else
    Auctionator.Utilities.Message(self:NextScanMessage())
  end
end

function AuctionatorFullScanFrameMixin:CanInitiate()
  local _, canDoGetAll = CanSendAuctionQuery()
  return canDoGetAll
end

function AuctionatorFullScanFrameMixin:NextScanMessage()
  local timeSinceLastScan = time() - (self.state.TimeOfLastGetAllScan or 0)
  local minutesUntilNextScan = 15 - math.ceil(timeSinceLastScan / 60)
  local secondsUntilNextScan = (15 * 60 - timeSinceLastScan) % 60

  return AUCTIONATOR_L_NEXT_SCAN_MESSAGE:format(minutesUntilNextScan, secondsUntilNextScan)
end

function AuctionatorFullScanFrameMixin:RegisterForEvents()
  Auctionator.Debug.Message("AuctionatorFullScanFrameMixin:RegisterForEvents()")

  self.otherFramesForEvent = { GetFramesRegisteredForEvent("AUCTION_ITEM_LIST_UPDATE") }
  for _, f in ipairs(self.otherFramesForEvent) do
    f:UnregisterEvent("AUCTION_ITEM_LIST_UPDATE")
  end

  FrameUtil.RegisterFrameForEvents(self, FULL_SCAN_EVENTS)
end

function AuctionatorFullScanFrameMixin:UnregisterForEvents()
  Auctionator.Debug.Message("AuctionatorFullScanFrameMixin:UnregisterForEvents()")

  for _, f in ipairs(self.otherFramesForEvent or {}) do
    f:RegisterEvent("AUCTION_ITEM_LIST_UPDATE")
  end

  FrameUtil.UnregisterFrameForEvents(self, FULL_SCAN_EVENTS)
end

function AuctionatorFullScanFrameMixin:CacheScanData()
  -- 20% complete after server response
  Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanProgress, 0.2)

  self:ResetData()
  self.totalAuctions = GetNumAuctionItems("list") or 0
  self.waitingForData = self.totalAuctions

  if self.totalAuctions <= 0 then
    self.cacheEnumerationComplete = true
    self:EndProcessing()
    return
  end

  -- Legacy AH result indices are 1..N. The previous integrated build began at
  -- index 0 and therefore could skip the final auction row.
  self:ProcessBatch(1, self.totalAuctions)
end

local function GetLegacyTimeLeftBand(index)
  local value = GetAuctionItemTimeLeft("list", index)
  if type(value) ~= "number" then
    return nil
  end

  -- Blizzard legacy API uses 1..4; Auctionator normalizes to 0..3.
  return value - 1
end

function AuctionatorFullScanFrameMixin:MaybeFinishCaching()
  if not self.inProgress or not self.cacheEnumerationComplete then
    return
  end

  if (self.waitingForData or 0) <= 0 then
    self.waitingForData = 0
    self:EndProcessing()
  end
end

function AuctionatorFullScanFrameMixin:WaitForOutstandingData()
  if self.cacheTimeoutStarted or not self.inProgress then
    return
  end

  self.cacheTimeoutStarted = true
  local startedAt = GetTime()

  local function CheckOutstanding()
    if not self.inProgress then
      return
    end

    if (self.waitingForData or 0) <= 0 then
      self.waitingForData = 0
      self:EndProcessing()
      return
    end

    if GetTime() - startedAt >= CACHE_DATA_TIMEOUT_SECONDS then
      self.unresolvedAuctions = self.waitingForData or 0
      self.waitingForData = 0
      self:EndProcessing()
      return
    end

    C_Timer.After(0.05, CheckOutstanding)
  end

  C_Timer.After(0.05, CheckOutstanding)
end

function AuctionatorFullScanFrameMixin:MarkAuctionResolved()
  self.waitingForData = math.max(0, (self.waitingForData or 1) - 1)
  self:MaybeFinishCaching()
end

function AuctionatorFullScanFrameMixin:StoreAuction(index, info, link)
  Auctionator.Utilities.DBKeyFromLink(link, function(dbKeys)
    if not self.inProgress then
      return
    end

    if dbKeys and #dbKeys > 0 then
      table.insert(self.scanData, {
        auctionInfo = info or { GetAuctionItemInfo("list", index) },
        itemLink = link,
        timeLeft = GetLegacyTimeLeftBand(index),
      })
      table.insert(self.dbKeysMapping, dbKeys)
    else
      self.skippedAuctions = (self.skippedAuctions or 0) + 1
    end

    self:MarkAuctionResolved()
  end)
end

function AuctionatorFullScanFrameMixin:ProcessAuctionIndex(index)
  local info = { GetAuctionItemInfo("list", index) }
  local link = GetAuctionItemLink("list", index)
  local itemID = info[Auctionator.Constants.AuctionItemInfo.ItemID]

  if type(itemID) ~= "number" or itemID <= 0 then
    self.skippedAuctions = (self.skippedAuctions or 0) + 1
    self:MarkAuctionResolved()
    return
  end

  if link and C_Item.GetItemInfoInstant(itemID) ~= nil then
    self:StoreAuction(index, info, link)
    return
  end

  -- Missing item/link data is common on a cold client cache. Ask Blizzard's
  -- item object to finish loading instead of immediately discarding the row.
  local item = Item:CreateFromItemID(itemID)
  item:ContinueOnItemLoad(function()
    if not self.inProgress then
      return
    end

    local loadedLink = GetAuctionItemLink("list", index)
    if not loadedLink then
      self.skippedAuctions = (self.skippedAuctions or 0) + 1
      self:MarkAuctionResolved()
      return
    end

    self:StoreAuction(index, { GetAuctionItemInfo("list", index) }, loadedLink)
  end)
end

function AuctionatorFullScanFrameMixin:ProcessBatch(startIndex, limit)
  if not self.inProgress then
    return
  end

  if startIndex > limit then
    self.cacheEnumerationComplete = true
    self:MaybeFinishCaching()
    if (self.waitingForData or 0) > 0 then
      self:WaitForOutstandingData()
    end
    return
  end

  -- 20-55%: copying/normalizing Blizzard's result rows.
  Auctionator.EventBus:Fire(self,
    Auctionator.FullScan.Events.ScanProgress,
    0.2 + ((startIndex - 1) / limit) * 0.35
  )

  local frameStart = debugprofilestop()
  local index = startIndex
  local processed = 0

  while index <= limit and processed < CACHE_MAX_ROWS do
    if processed >= CACHE_MIN_ROWS
        and debugprofilestop() - frameStart >= CACHE_FRAME_BUDGET_MS then
      break
    end

    self:ProcessAuctionIndex(index)
    index = index + 1
    processed = processed + 1
  end

  if index > limit then
    self.cacheEnumerationComplete = true
    self:MaybeFinishCaching()
    if self.inProgress and (self.waitingForData or 0) > 0 then
      self:WaitForOutstandingData()
    end
  else
    C_Timer.After(0, function()
      self:ProcessBatch(index, limit)
    end)
  end
end

function AuctionatorFullScanFrameMixin:OnEvent(event, ...)
  if event == "AUCTION_ITEM_LIST_UPDATE" then
    Auctionator.Debug.Message(event)

    FrameUtil.UnregisterFrameForEvents(self, { "AUCTION_ITEM_LIST_UPDATE" })
    self:CacheScanData()
  elseif event == "AUCTION_HOUSE_CLOSED" then
    self:UnregisterForEvents()

    if self.inProgress then
      self.inProgress = false
      self:ResetData()

      Auctionator.Utilities.Message(
        AUCTIONATOR_L_FULL_SCAN_FAILED .. " " .. self:NextScanMessage()
      )
      Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanFailed)
    end
  end
end

local function GetInfo(auctionInfo)
  local available = tonumber(auctionInfo[3]) or 0
  local buyoutPrice = tonumber(auctionInfo[10]) or 0

  if available <= 0 or buyoutPrice <= 0 then
    return nil, available
  end

  return math.ceil(buyoutPrice / available), available
end

local function MergeInfo(scanData, dbKeysMapping, callback, progressCallback)
  local allInfo = {}
  local index = 1
  local total = #scanData

  if total == 0 then
    callback(allInfo)
    return
  end

  local function ProcessMergeBatch()
    local frameStart = debugprofilestop()
    local processed = 0

    while index <= total and processed < MERGE_MAX_ROWS do
      if processed >= MERGE_MIN_ROWS
          and debugprofilestop() - frameStart >= MERGE_FRAME_BUDGET_MS then
        break
      end

      local scanEntry = scanData[index]
      local effectivePrice, available = GetInfo(scanEntry.auctionInfo)

      if available > 0 and effectivePrice and effectivePrice > 0 then
        local owner = scanEntry.auctionInfo[Auctionator.Constants.AuctionItemInfo.Owner]
        local dbKeys = dbKeysMapping[index] or {}

        for _, dbKey in ipairs(dbKeys) do
          if allInfo[dbKey] == nil then
            allInfo[dbKey] = {}
          end

          table.insert(allInfo[dbKey], {
            price = effectivePrice,
            available = available,
            timeLeft = scanEntry.timeLeft,
            owner = owner,
          })
        end
      end

      index = index + 1
      processed = processed + 1
    end

    if progressCallback then
      progressCallback(math.min(1, (index - 1) / total))
    end

    if index > total then
      callback(allInfo)
    else
      C_Timer.After(0, ProcessMergeBatch)
    end
  end

  ProcessMergeBatch()
end

function AuctionatorFullScanFrameMixin:EndProcessing()
  if not self.inProgress then
    return
  end

  self.inProgress = false
  self:UnregisterForEvents()

  local rawFullScan = self.scanData
  local dbKeysMapping = self.dbKeysMapping
  local totalAuctions = self.totalAuctions or #rawFullScan
  local skippedAuctions = self.skippedAuctions or 0
  local unresolvedAuctions = self.unresolvedAuctions or 0
  local scanStartProfile = self.scanStartProfile or debugprofilestop()

  -- Detach the working tables so a later scan can safely start even while the
  -- cooperative merge/database callbacks from this scan are completing.
  self:ResetData()

  Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanProgress, 0.55)

  MergeInfo(rawFullScan, dbKeysMapping, function(allInfo)
    Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanProgress, 0.75)

    Auctionator.Database:ProcessScan(allInfo, function(count)
      local elapsedSeconds = math.max(0, (debugprofilestop() - scanStartProfile) / 1000)
      local cachedAuctions = #rawFullScan
      local quality = 1

      if totalAuctions > 0 then
        quality = math.max(0, math.min(1, cachedAuctions / totalAuctions))
      end

      local seenKeys = {}
      for dbKey in pairs(allInfo) do
        seenKeys[dbKey] = true
      end
      local absentWatchedItems =
        Auctionator.Database:RecordAbsentWatchedItems(seenKeys, quality)

      local stats = {
        totalAuctions = totalAuctions,
        cachedAuctions = cachedAuctions,
        skippedAuctions = skippedAuctions,
        unresolvedAuctions = unresolvedAuctions,
        itemKeys = count,
        elapsedSeconds = elapsedSeconds,
        quality = quality,
        absentWatchedItems = absentWatchedItems,
      }

      Auctionator.State.LastFullScanStats = stats

      Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanProgress, 0.99)
      Auctionator.EventBus:Fire(self, Auctionator.FullScan.Events.ScanComplete, rawFullScan, stats)

      local qualityPercent = math.floor(quality * 100 + 0.5)
      Auctionator.Utilities.Message(
        AUCTIONATOR_L_FINISHED_PROCESSING:format(count)
          .. string.format(
            " | %d auctions | %.1fs | quality %d%% | %d watched absences",
            cachedAuctions,
            elapsedSeconds,
            qualityPercent,
            absentWatchedItems
          )
      )
    end, function(databaseProgress)
      Auctionator.EventBus:Fire(self,
        Auctionator.FullScan.Events.ScanProgress,
        0.75 + math.min(1, databaseProgress or 0) * 0.24
      )
    end)
  end, function(mergeProgress)
    Auctionator.EventBus:Fire(self,
      Auctionator.FullScan.Events.ScanProgress,
      0.55 + math.min(1, mergeProgress or 0) * 0.20
    )
  end)
end
